on:
  push:
    branches:
      - main
name: Deploy main on Push
jobs:
  web-deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - name: Get latest code
      uses: actions/checkout@v2

    - name: Use production env
      run: cp .env.example .env   

    - name: Install vendors
      run: composer install --no-dev --optimize-autoloader

    - name: Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server: iad1-shared-e1-05.dreamhost.com
        username: dh_6va2ha
        password: Maneth@12